### ISSUE TITLE
Remove button should have a larger top margin

### ISSUE THREAD

**Issue by artlogic** [arsmentis/rusnack-pd#16]
I think it needs to be separated from the main content so it can't be accidentally clicked on as easily, and also so that it visually has more impact.

**Comment by SKBruck** [comment]
Need review - let me know if other buttons should be made larger

**Comment by artlogic** [comment]
I do think it looks a bit odd the difference in button size. Can you resolve that?

**Comment by SKBruck** [comment]
Better?

**Comment by artlogic** [comment]
Looks good.
