### ISSUE TITLE
Figure out better UX for uploading files vs. submitting the entire form

### ISSUE THREAD

**Issue by artlogic** [arsmentis/rusnack-pd#5]

**Comment by artlogic** [comment]
I don't see an "Upload Drawings" section.

**Comment by SKBruck** [comment]
It's the second tab - the green tab under Material Size.

**Comment by artlogic** [comment]
You appear to have it hidden.

**Comment by SKBruck** [comment]
The Upload Drawings tab is back up - could you review this solution in light of my comments above?

**Comment by artlogic** [comment]
Looks good!
